description: GTR

target:
  service: sing
  name: msroctovc

storage:
  data:
    storage_account_name: scim
    container_name: v-yifangxu

environment:
  image: v-yuczhao/vit:pytorch1.11.0
  registry: msraimsouthcentralus.azurecr.io
  username: msraimsouthcentralus
  setup:
    - pip install terminaltables easydict h5py nltk timm ptflops einops fvcore
    - export PYTHONPATH=$PYTHONPATH:/tmp/code/XYF

code:
  code_upload: True
  local_dir: $CONFIG_DIR/../

jobs:
 - name: GTR
   sku: G8-V100
   command:
     - echo ready!
     - echo ready!!
     - echo ready!!!
     - sleep 1d

     - cd /tmp/code/XYF/data
     - wget -c https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz
     - tar -xzvf azcopy_linux_amd64_10.13.0.tar.gz
     - azcopy_linux_amd64_10.13.0/azcopy copy 'https://scim.blob.core.windows.net/v-yifangxu/Video Grounding/TACoS?sv=2020-10-02&st=2022-04-09T09%3A00%3A23Z&se=2023-06-10T09%3A00%3A00Z&sr=c&sp=rl&sig=giMpvZi75VZ063DbN2ZsuDo03Pp8581J%2BWHXl%2FfIjzU%3D' ./ --recursive

     - cd /tmp/code/XYF
     - python moment_localization/run.py --cfg experiments/tacos/GTR.yaml --logDir $$AMLT_OUTPUT_DIR --verbose --tag base


   submit_args:
     container_args:
       shm_size: 64g
   sla_tier: basic  # Default: premium
   execution_mode: basic  # Default: basic
   priority: high  # Default: medium